name: gem-dqm-analysis-py39
channels:
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - beautifulsoup4 
    - root
    - cx_oracle
    - uproot
    - hist
    - mplhep 
    - numpy
    - tqdm
    - cx_oracle
    - pandas
    - pip:
        - git+ssh://git@gitlab.cern.ch:7999/cmsoms/oms-api-client.git
